### LOGIN

POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "pipo1@outlook.es",
    "password": "secret"
}

### BLOGS

GET http://localhost:3001/api/blogs
content-type: application/json

###

GET http://localhost:3001/api/blogs?search=author
content-type: application/json"

###

POST http://localhost:3001/api/blogs
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpcG8xQG91dGxvb2suZXMiLCJpZCI6MSwiaWF0IjoxNzIxMjI2MzQ2fQ.fryUFuxR48rb_yZSkeTwfyZJJVfVnQwiTcpYzU9zepA

{
    "author": "Dario",
    "url": "Test",
    "title": "Other title",
    "likes": 2,
    "year": 1994
}

###

DELETE http://localhost:3001/api/blogs/7
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpcG9Ab3V0bG9vay5lcyIsImlkIjoyLCJpYXQiOjE3MjEwNjY3MDd9.vaiN6rWEVWx6ggwH5aZ9vA-1D_heMS0JSmKwZFPm1M0

###

PUT http://localhost:3001/api/blogs/6
content-type: application/json

{
    "likes": 7
}

### AUTHORS

GET http://localhost:3001/api/authors
content-type: application/json

### USERS

GET http://localhost:3001/api/users
content-type: application/json

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "pipo1@outlook.es",
    "name": "Pepe Peres"
}

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "pipo",
    "name": "Pepe Peres"
}

###

PUT http://localhost:3001/api/users/pipo
content-type: application/json

{
    "username": "pipo11"
}